# Generated by Django 4.1 on 2023-02-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_item_sales_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="sales_category",
            field=models.CharField(
                choices=[
                    ("BS", "best sellers"),
                    ("NA", "new aqrrivals"),
                    ("HS", "hot sales"),
                ],
                max_length=2,
            ),
        ),
    ]
